root: /
permalink: /:year-:month/:title/
markdown: redcarpet
pygments: true
paginate: 5
url: http://boarderline_chaotic.com
baseurl: /
layouts: ./_layouts
exclude: [2013-01-27-markdown-howto.md, 2014-03-09-welcome-to-jekyll.markdown, 2013-10-23-Design-Deploy-Service.md]
port: 4000
url: http://localhost:4000

title: BorderlineChaotic 
